# Site Information
title                   : read; write; learn;
tagline                 :
author                  : Lisa Rosenberg
email                   : lisa.rosenberg@outlook.de
description             : >-
  Hi! I'm Lisa.
  This is my blog about software development related topics.
  I want to write down my experiences and things I have learned - so why not sharing them online?
  There will be posts about a single topic as well as (hopefully) monthly posts containing things I have learned that month.
keywords                : "Software, Development, Lessons, Learned, Jekyll, Blog"
baseurl                 : "" # the subpath of the site, e.g. /blog
url                     : "https://lisa-rosenberg.github.io" # the base hostname & protocol for the site, e.g. http://example.com
locale                  : en_US

# Author Information
twitter_username        : rosenbeli
github_username         : lisa-rosenberg
xing_username           : Lisa_Rosenberg3
linkedin_username       : lisa-rosenberg-206a93142
disqus_shortname        :
favicon                 : "/assets/images/page/favicon.ico"
aboutme                 :
aboutme_photo           : "/assets/images/page/profile.jpg"
google_analytics_key    :

# Site Settings
ShowContactInfo         : "true"
default_column          : "two"
default_locale          : "en"

locales:
  en:
    Home                : "Home"
    Categories          : "Categories"
    Recent_Posts        : "Recent Posts"
    Tags                : "Tags"
    Archives            : "Archives"

    Previous            : "Older"
    Next                : "Newer"

    PostedInCategories  : "Posted in"
    Taggedwith          : "Tags: "
    PostDate            : "on "

# Build Settings
markdown                : kramdown
kramdown:
  input                 : GFM
  syntax_highlighter    : rouge
  parse_block_html      : true
paginate                : 5
excerpt_separator       : <!-- more -->
plugins:
  - jekyll-paginate
  - jekyll-toc

# Reading files
exclude:
  - .idea
  - .gitignore
  - .travis.yml
  - lisa-rosenberg.github.io.iml
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - .sass-cache
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache

keep_files:
  - .git